config/routes.rb
Rails.application.routes.draw do
  resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.all
	end

	def show
		@product = Product.find(params[:id])
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)
		if @product.save
			redirect_to products_path
		else
			render :new
		end
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])
		if @product.update(product_params)
			redirect_to products_path
		else
			render :edit
		end
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		redirect_to products_path
	end

	private 
	def product_params
		params.require(:product).permit(:name, :stock)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapplication</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/edit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Update Product</title>
</head>
<body>

	<div class="container">
		<div class="row">
			<%= form_for @product do |f| %>
			<div class="form-group" style="margin-top: 30px">
				<%= f.label :name %>
				<%= f.text_field :name, class: "form-control" %>
			</div>
			<div>
				<%= f.label :stock %>
				<%= f.number_field :stock, class: "form-control" %>
			</div>
			<div>
				<%= f.submit class: "btn btn-primary", style: "margin-top:30px" %>
			</div>
			<% end %>
		</div>
	</div>

</body>
</html>

app/views/products/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>My Application With Ruby on Rails</title>
</head>
<body>
	<div class="container">
		<div class="row">
			<%= link_to "create product", new_product_path, class: "btn btn-success", style:"margin-top:30px; margin-bottom:30px" %>
			<table class="table table-bordered table-hover table-responsive">
				<thead>
					<th>Name Product</th>
					<th>Stock Product</th>
					<th colspan="2">Action</th>
				</thead>
				<% @products.each do |product|  %>
				<tr>
					<td><%= product.name %></td>
					<td><%= product.stock %></td>
					<td><%= link_to "Edit", edit_product_path(product), class: "btn btn-primary" %></td>
					<td><%= link_to "Delete", product, method: :delete,class: "btn btn-danger", data: { confirm: "Are you sure want to delete" } %></td>
				</tr>
				<% end %>
			</table>
		</div>
	</div>

</body>
</html>

app/views/products/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Create Product</title>
</head>
<body>
	<div class="container">
		<div class="row">
			<%= form_for @product do |f| %>
			<div class="form-group">
				<%= f.label :name_product, style: "margin-top:30px" %>
				<%= f.text_field :name, class: "form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :stock %>
				<%= f.number_field :stock, class: "form-control" %>
			</div>
			<div>
				<%= f.submit class: "btn btn-primary" %>
			</div>
			<% end %>
		</div>
	</div>

</body>
</html>